### PR TITLE
Use stable const-fn

### PR DESCRIPTION
**Pull request by Disasm**

### CODE REVIEW

**Comment by Disasm** [comment]
Additionally, this change unlocks static Mutex constructions on stable.

**Comment by burrbull** [comment]
@japaric can you merge this PR, and https://github.com/japaric/vcell/pull/9 , please.
It will not take much time.

**Comment by Disasm** [comment]
@burrbull There is a good temporary solution (at least non-breaking one): https://github.com/rust-embedded/cortex-m/pull/159

**Comment by burrbull** [comment]
https://docs.rs/autocfg/0.1.5/autocfg/ has `probe_rustc_version` method:

https://github.com/rust-num/num-complex/pull/63/files

**Comment by burrbull** [comment]
cc @adamgreig

**Pull request merged**
